
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 110104 
    driver-class-name: com.mysql.cj.jdbc.Driver

spring.security.user.name: admin
spring.security.user.password: 110104